// WARNING: This file has automatically been generated on Thu, 18 Apr 2024 15:59:58 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "tcml.h"
#include "stdlib.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

