// WARNING: This file has automatically been generated on Thu, 18 Apr 2024 15:59:58 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package tcml

/*
#include "tcml.h"
#include "stdlib.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// DEVICE_PCI_BUS_ID_BUFFER_SIZE as defined in ts_c4go/tcml.h:183
	DEVICE_PCI_BUS_ID_BUFFER_SIZE = 32
	// DEVICE_PCI_BUS_ID_BUFFER_V2_SIZE as defined in ts_c4go/tcml.h:188
	DEVICE_PCI_BUS_ID_BUFFER_V2_SIZE = 16
	// DEVICE_PCI_BUS_ID_LEGACY_FMT as defined in ts_c4go/tcml.h:217
	DEVICE_PCI_BUS_ID_LEGACY_FMT = "%04X:%02X:%02X.%X"
	// DEVICE_PCI_BUS_ID_FMT as defined in ts_c4go/tcml.h:222
	DEVICE_PCI_BUS_ID_FMT = "%08X:%02X:%02X.%X"
)

// Return as declared in ts_c4go/tcml.h:92
type Return int32

// Return enumeration from ts_c4go/tcml.h:92
const (
	SUCCESS                   Return = iota
	ERROR_INVALID_ARGS        Return = 1
	ERROR_NOT_SUPPORTED       Return = 2
	ERROR_FILE_ERROR          Return = 3
	ERROR_PERMISSION          Return = 4
	ERROR_OUT_OF_RESOURCES    Return = 5
	ERROR_INTERNAL_EXCEPTION  Return = 6
	ERROR_INPUT_OUT_OF_BOUNDS Return = 7
	ERROR_INIT_ERROR          Return = 8
	ERROR_NOT_YET_IMPLEMENTED Return = 9
	ERROR_NOT_FOUND           Return = 10
	ERROR_INSUFFICIENT_SIZE   Return = 11
	ERROR_INTERRUPT           Return = 12
	ERROR_UNEXPECTED_SIZE     Return = 13
	ERROR_NO_DATA             Return = 14
	ERROR_UNEXPECTED_DATA     Return = 15
	ERROR_BUSY                Return = 16
	ERROR_REFCOUNT_OVERFLOW   Return = 17
	ERROR_UNKNOWN_ERROR       Return = 4294967295
)

// ClockType as declared in ts_c4go/tcml.h:100
type ClockType int32

// ClockType enumeration from ts_c4go/tcml.h:100
const (
	CLOCK_MPE   ClockType = iota
	CLOCK_SPE   ClockType = 1
	CLOCK_HBM   ClockType = 2
	CLOCK_GLB   ClockType = 3
	CLOCK_COUNT ClockType = 4
)

// CardTopologyLevel as declared in ts_c4go/tcml.h:131
type CardTopologyLevel int32

// CardTopologyLevel enumeration from ts_c4go/tcml.h:131
const (
	TOPOLOGY_INTERNAL   CardTopologyLevel = iota
	TOPOLOGY_SINGLE     CardTopologyLevel = 10
	TOPOLOGY_MULTIPLE   CardTopologyLevel = 20
	TOPOLOGY_HOSTBRIDGE CardTopologyLevel = 30
	TOPOLOGY_NODE       CardTopologyLevel = 40
	TOPOLOGY_SYSTEM     CardTopologyLevel = 50
)

// CardP2PStatus as declared in ts_c4go/tcml.h:138
type CardP2PStatus int32

// CardP2PStatus enumeration from ts_c4go/tcml.h:138
const (
	P2P_STATUS_OK            CardP2PStatus = iota
	P2P_STATUS_NOT_SUPPORTED CardP2PStatus = 1
	P2P_STATUS_UNKNOWN       CardP2PStatus = 2
)

// CardP2PCapsIndex as declared in ts_c4go/tcml.h:145
type CardP2PCapsIndex int32

// CardP2PCapsIndex enumeration from ts_c4go/tcml.h:145
const (
	P2P_CAPS_INDEX_READ    CardP2PCapsIndex = iota
	P2P_CAPS_INDEX_WRITE   CardP2PCapsIndex = 1
	P2P_CAPS_INDEX_UNKNOWN CardP2PCapsIndex = 2
)

// PcieUtilCounter as declared in ts_c4go/tcml.h:156
type PcieUtilCounter int32

// PcieUtilCounter enumeration from ts_c4go/tcml.h:156
const (
	PCIE_UTIL_TX_BYTES PcieUtilCounter = iota
	PCIE_UTIL_RX_BYTES PcieUtilCounter = 1
	PCIE_UTIL_COUNT    PcieUtilCounter = 2
)

// TemperatureThresholds as declared in ts_c4go/tcml.h:168
type TemperatureThresholds int32

// TemperatureThresholds enumeration from ts_c4go/tcml.h:168
const (
	TEMPERATURE_THRESHOLD_SHUTDOWN TemperatureThresholds = iota
	TEMPERATURE_THRESHOLD_SLOWDOWN TemperatureThresholds = 1
	TEMPERATURE_THRESHOLD_COUNT    TemperatureThresholds = 2
)

// PerfPolicyType as declared in ts_c4go/tcml.h:178
type PerfPolicyType int32

// PerfPolicyType enumeration from ts_c4go/tcml.h:178
const (
	PERF_POLICY_THERMAL PerfPolicyType = iota
	PERF_POLICY_COUNT   PerfPolicyType = 1
)
