// WARNING: This file has automatically been generated on Thu, 18 Apr 2024 15:59:58 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package go-tcml provides Go bindings for tcml implementation
*/
package tcml
