// WARNING: This file has automatically been generated on Thu, 18 Apr 2024 15:59:58 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package tcml

/*
#include "tcml.h"
#include "stdlib.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// Utilization as declared in ts_c4go/tcml.h:105
type Utilization struct {
	Gpu            uint32
	Memory         uint32
	refaa2e28e9    *C.tcmlUtilization_t
	allocsaa2e28e9 interface{}
}

// Memory as declared in ts_c4go/tcml.h:111
type Memory struct {
	Total          uint64
	Free           uint64
	Used           uint64
	ref3fa2f6bd    *C.tcmlMemory_t
	allocs3fa2f6bd interface{}
}

// Clock as declared in ts_c4go/tcml.h:116
type Clock struct {
	Current        uint64
	Max            uint64
	ref23293422    *C.tcmlClock_t
	allocs23293422 interface{}
}

// PciInfo as declared in ts_c4go/tcml.h:212
type PciInfo struct {
	BusIdLegacy    [16]byte
	Domain         uint32
	Bus            uint32
	Device         uint32
	Function       uint32
	PciDeviceId    uint32
	PciSubSystemId uint32
	BusId          [32]byte
	ref71ae7c45    *C.tcmlPciInfo_t
	allocs71ae7c45 interface{}
}
